steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/vera-contextual-model-server', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/vera-contextual-model-server']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'vera-contextual-model-server', 
  '--image', ' gcr.io/$PROJECT_ID/vera-contextual-model-server',  
  '--region', 'asia-south1', 
  '--platform', 'managed', 
  '--allow-unauthenticated',
  '--service-account=${_SERVICE_ACCOUNT}',
  '--set-env-vars=DB_CONNECT=${_DB_CONNECT}',
  '--set-env-vars=DB_NAME=${_DB_NAME}',
  '--set-env-vars=PINECONE_KEY=${_PINECONE_KEY}']
substitutions:
    _DB_CONNECT: $DB_CONNECT
    _DB_NAME: $DB_NAME
    _PINECONE_KEY: $PINECONE_KEY
    _SERVICE_ACCOUNT: $SERVICE_ACCOUNT
    
images:
- 'gcr.io/$PROJECT_ID/vera-contextual-model-server'